# Generated by Django 4.0.3 on 2022-04-21 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asosiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminTel', models.CharField(max_length=100)),
                ('telegramLink', models.URLField(max_length=100)),
                ('instagramLink', models.URLField(max_length=100)),
                ('ishVaqtiRU', models.CharField(max_length=100)),
                ('ishVaqtiUZ', models.CharField(max_length=100)),
                ('manzilRU', models.CharField(max_length=100)),
                ('manzilUZ', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kansultatsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Klent', models.CharField(max_length=300)),
                ('telNumberKlent', models.CharField(max_length=300)),
                ('date_time', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='kategoryuzRU')),
                ('description', models.CharField(max_length=400, verbose_name='kategoryruUZ')),
                ('CategoriyaName', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Naduvnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('eskiNarh', models.CharField(max_length=300)),
                ('hozirgiNarh', models.CharField(max_length=300)),
                ('nechtaligi', models.CharField(max_length=300)),
                ('ramkaRu', models.CharField(max_length=200)),
                ('razmer', models.CharField(max_length=300)),
                ('chuqurligi', models.CharField(max_length=300)),
                ('comment', models.TextField(max_length=3000)),
                ('ramkaUz', models.CharField(max_length=20)),
                ('kamplektatsiyARu1', models.CharField(max_length=200, verbose_name='kamplektatsiyaRu1')),
                ('kamplektatsiyAUz', models.CharField(max_length=200, verbose_name='kamplektatsiyaUz')),
                ('categoriya', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('telNumber', models.CharField(max_length=200)),
                ('poolFrame', models.CharField(max_length=200)),
                ('money', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('date_time', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Karkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('eskiNarh', models.CharField(max_length=300)),
                ('hozirgiNarh', models.CharField(max_length=300)),
                ('nechtaligi', models.CharField(max_length=300)),
                ('ramkaRu', models.CharField(max_length=200)),
                ('razmer', models.CharField(max_length=300)),
                ('chuqurligi', models.CharField(max_length=300)),
                ('commentUZ', models.TextField(max_length=3000, verbose_name='commentUZ')),
                ('commentRU', models.TextField(max_length=3000, verbose_name='commentRU')),
                ('ramkaUz', models.CharField(max_length=20)),
                ('kamplektatsiyARu1', models.CharField(max_length=200, verbose_name='kamplektatsiyARu1')),
                ('kamplektatsiyAUz', models.CharField(max_length=200, verbose_name='kamplektatsiyAUz')),
                ('categoriya', models.CharField(max_length=200)),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.kategoriya')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
