# Generated by Django 4.0.1 on 2022-05-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='customer',
        ),
    ]
