# Generated by Django 4.0.3 on 2022-04-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kansultatsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Klent', models.CharField(max_length=300)),
                ('telNumberKlent', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Karkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('latestCost', models.CharField(max_length=200)),
                ('nowCost', models.CharField(max_length=200)),
                ('howMuch', models.CharField(max_length=200)),
                ('frame', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('deep', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Naduvnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('latestCost', models.CharField(max_length=200)),
                ('nowCost', models.CharField(max_length=200)),
                ('howMuch', models.CharField(max_length=200)),
                ('frame', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('deep', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('telNumber', models.CharField(max_length=200)),
                ('poolFrame', models.CharField(max_length=200)),
                ('money', models.CharField(max_length=200)),
            ],
        ),
    ]
